name: Doxygen Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.8
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "."
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        submodules: false
